test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_square_root (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 33, in test_square_root
    'Failed to calculate square roots'
AssertionError: Lists differ: [(1, 5), (1, 5), (1, 5), (1, 5), (1, 5), ([753 chars], 5)] != [0.0, 1.0, 1.4142135623730951, 1.732050807[1699 chars]0662]

First differing element 0:
(1, 5)
0.0

Diff is 3146 characters long. Set self.maxDiff to None to see it. : Failed to calculate square roots

----------------------------------------------------------------------
Ran 2 tests in 0.013s

FAILED (failures=1)
